// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	message.proto
	type.proto
	xcode.proto

It has these top-level messages:
	Message
	EndPoint
	HandShake
	HandShakeResponse
	Ping
	Instruction
	Instruction_Start
	InstructionUnit
	Instruction_Init
	Instruction_Invoke
	Instruction_Query
	Instruction_State
	XCodeSpec
	XCodeStateSpec
	XCodeID
	XCodeInput
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Action int32

const (
	Action_Request  Action = 0
	Action_Response Action = 1
)

var Action_name = map[int32]string{
	0: "Request",
	1: "Response",
}
var Action_value = map[string]int32{
	"Request":  0,
	"Response": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message_Type int32

const (
	Message_UNDEFINED           Message_Type = 0
	Message_Net_HANDSHAKE       Message_Type = 1
	Message_Net_PING            Message_Type = 2
	Message_Contract_Deploy     Message_Type = 3
	Message_Contract_Run        Message_Type = 4
	Message_Contract_Query      Message_Type = 5
	Message_Code                Message_Type = 6
	Message_Ledger_Block_Create Message_Type = 7
	Message_Ledger_Block_Sync   Message_Type = 8
	Message_Identity_Share      Message_Type = 9
	Message_Error               Message_Type = 10
	Message_OK                  Message_Type = 11
)

var Message_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "Net_HANDSHAKE",
	2:  "Net_PING",
	3:  "Contract_Deploy",
	4:  "Contract_Run",
	5:  "Contract_Query",
	6:  "Code",
	7:  "Ledger_Block_Create",
	8:  "Ledger_Block_Sync",
	9:  "Identity_Share",
	10: "Error",
	11: "OK",
}
var Message_Type_value = map[string]int32{
	"UNDEFINED":           0,
	"Net_HANDSHAKE":       1,
	"Net_PING":            2,
	"Contract_Deploy":     3,
	"Contract_Run":        4,
	"Contract_Query":      5,
	"Code":                6,
	"Ledger_Block_Create": 7,
	"Ledger_Block_Sync":   8,
	"Identity_Share":      9,
	"Error":               10,
	"OK":                  11,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	Action    Action                     `protobuf:"varint,1,opt,name=action,enum=protos.Action" json:"action,omitempty"`
	Type      Message_Type               `protobuf:"varint,2,opt,name=type,enum=protos.Message_Type" json:"type,omitempty"`
	Payload   []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterEnum("protos.Action", Action_name, Action_value)
	proto.RegisterEnum("protos.Message_Type", Message_Type_name, Message_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Net service

type NetClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Net_ConnectClient, error)
}

type netClient struct {
	cc *grpc.ClientConn
}

func NewNetClient(cc *grpc.ClientConn) NetClient {
	return &netClient{cc}
}

func (c *netClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Net_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Net_serviceDesc.Streams[0], c.cc, "/protos.net/connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &netConnectClient{stream}
	return x, nil
}

type Net_ConnectClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type netConnectClient struct {
	grpc.ClientStream
}

func (x *netConnectClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *netConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Net service

type NetServer interface {
	Connect(Net_ConnectServer) error
}

func RegisterNetServer(s *grpc.Server, srv NetServer) {
	s.RegisterService(&_Net_serviceDesc, srv)
}

func _Net_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetServer).Connect(&netConnectServer{stream})
}

type Net_ConnectServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type netConnectServer struct {
	grpc.ServerStream
}

func (x *netConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *netConnectServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Net_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.net",
	HandlerType: (*NetServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "connect",
			Handler:       _Net_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xeb, 0xc4, 0xb5, 0x93, 0xc9, 0x9f, 0x6e, 0xa7, 0x20, 0xac, 0x5c, 0x40, 0x41, 0x42,
	0x11, 0x07, 0x17, 0xc2, 0xa5, 0xd7, 0x10, 0x1b, 0x1a, 0x15, 0x0c, 0x38, 0xe5, 0x6c, 0xb9, 0xf6,
	0x60, 0x22, 0xdc, 0x5d, 0xb3, 0x5e, 0x1f, 0x7c, 0xe7, 0x13, 0xf2, 0x89, 0xd8, 0xd8, 0x75, 0x50,
	0x73, 0x5a, 0xcd, 0x7b, 0xbf, 0x9d, 0x9d, 0x37, 0x5a, 0x98, 0xdc, 0x53, 0x59, 0xc6, 0x19, 0xb9,
	0x85, 0x14, 0x4a, 0xa0, 0xd5, 0x1c, 0xe5, 0xec, 0x79, 0x26, 0x44, 0x96, 0xd3, 0x65, 0x53, 0xde,
	0x55, 0x3f, 0x2e, 0xd5, 0x4e, 0x83, 0x2a, 0xbe, 0x2f, 0x5a, 0x70, 0xfe, 0xa7, 0x0f, 0xf6, 0xe7,
	0xf6, 0x2a, 0xbe, 0x02, 0x2b, 0x4e, 0xd4, 0x4e, 0x70, 0xc7, 0x78, 0x61, 0x2c, 0xa6, 0xcb, 0x69,
	0xcb, 0x94, 0xee, 0xaa, 0x51, 0xc3, 0x07, 0x17, 0x17, 0x60, 0xaa, 0xba, 0x20, 0xa7, 0xd7, 0x50,
	0x4f, 0x3a, 0xea, 0xa1, 0x8d, 0x7b, 0xab, 0xbd, 0xb0, 0x21, 0xd0, 0x01, 0xbb, 0x88, 0xeb, 0x5c,
	0xc4, 0xa9, 0xd3, 0xd7, 0xf0, 0x38, 0xec, 0x4a, 0xbc, 0x82, 0xe1, 0x61, 0x14, 0xc7, 0xd4, 0xde,
	0x68, 0x39, 0x73, 0xdb, 0x61, 0xdd, 0x6e, 0x58, 0xf7, 0xb6, 0x23, 0xc2, 0xff, 0xf0, 0xfc, 0xaf,
	0x01, 0xe6, 0xfe, 0x09, 0x9c, 0xc0, 0xf0, 0x7b, 0xe0, 0xf9, 0x1f, 0x36, 0x81, 0xef, 0xb1, 0x13,
	0x3c, 0x87, 0x49, 0x40, 0x2a, 0xba, 0x5e, 0x05, 0xde, 0xf6, 0x7a, 0x75, 0xe3, 0x33, 0x03, 0xc7,
	0x30, 0xd8, 0x4b, 0x5f, 0x37, 0xc1, 0x47, 0xd6, 0xc3, 0x0b, 0x38, 0x5b, 0x0b, 0xae, 0xa4, 0x4e,
	0x11, 0x79, 0x54, 0xe4, 0xa2, 0x66, 0x7d, 0x64, 0x30, 0x3e, 0x88, 0x61, 0xc5, 0x99, 0x89, 0x08,
	0xd3, 0x83, 0xf2, 0xad, 0x22, 0x59, 0xb3, 0x53, 0x1c, 0x80, 0xb9, 0x16, 0x29, 0x31, 0x0b, 0x9f,
	0xc1, 0xc5, 0x27, 0x4a, 0x33, 0x92, 0xd1, 0xfb, 0x5c, 0x24, 0xbf, 0xa2, 0xb5, 0xa4, 0x58, 0x11,
	0xb3, 0xf1, 0x29, 0x9c, 0x3f, 0x32, 0xb6, 0x35, 0x4f, 0xd8, 0x60, 0xdf, 0x6d, 0x93, 0x12, 0x57,
	0x3b, 0x55, 0x47, 0xdb, 0x9f, 0xb1, 0x24, 0x36, 0xc4, 0x21, 0x9c, 0xfa, 0x52, 0x0a, 0xc9, 0x00,
	0x2d, 0xe8, 0x7d, 0xb9, 0x61, 0xa3, 0xd7, 0x2f, 0xc1, 0x6a, 0x97, 0x8c, 0x23, 0xb0, 0x43, 0xfa,
	0x5d, 0xe9, 0xb0, 0x3a, 0x93, 0x0e, 0x10, 0x52, 0x59, 0x08, 0x5e, 0x12, 0x33, 0x96, 0x57, 0xd0,
	0xe7, 0xa4, 0xf0, 0x2d, 0xd8, 0x89, 0xe0, 0x9c, 0x12, 0x85, 0x67, 0x47, 0xbb, 0x9f, 0x1d, 0x0b,
	0xf3, 0x93, 0x85, 0xf1, 0xc6, 0xb8, 0x6b, 0xbf, 0xc3, 0xbb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0xe2, 0x09, 0xc2, 0x26, 0x02, 0x00, 0x00,
}
