// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	message.proto
	type.proto

It has these top-level messages:
	Message
	HandShake
	EndPoint
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_UNDEFINED     Type = 0
	Type_VALIDATOR     Type = 1
	Type_NON_VALIDATOR Type = 2
)

var Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "VALIDATOR",
	2: "NON_VALIDATOR",
}
var Type_value = map[string]int32{
	"UNDEFINED":     0,
	"VALIDATOR":     1,
	"NON_VALIDATOR": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Action int32

const (
	Action_Request  Action = 0
	Action_Response Action = 1
)

var Action_name = map[int32]string{
	0: "Request",
	1: "Response",
}
var Action_value = map[string]int32{
	"Request":  0,
	"Response": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Message_Type int32

const (
	Message_UNDEFINED           Message_Type = 0
	Message_Net_HANDSHAKE       Message_Type = 1
	Message_Net_PING            Message_Type = 2
	Message_Contract_Create     Message_Type = 3
	Message_Contract_Run        Message_Type = 4
	Message_Contract_Query      Message_Type = 5
	Message_Code_State_Put      Message_Type = 6
	Message_Code_State_Get      Message_Type = 7
	Message_Ledger_Block_Create Message_Type = 8
	Message_Ledger_Block_Sync   Message_Type = 9
	Message_Identity_Share      Message_Type = 10
)

var Message_Type_name = map[int32]string{
	0:  "UNDEFINED",
	1:  "Net_HANDSHAKE",
	2:  "Net_PING",
	3:  "Contract_Create",
	4:  "Contract_Run",
	5:  "Contract_Query",
	6:  "Code_State_Put",
	7:  "Code_State_Get",
	8:  "Ledger_Block_Create",
	9:  "Ledger_Block_Sync",
	10: "Identity_Share",
}
var Message_Type_value = map[string]int32{
	"UNDEFINED":           0,
	"Net_HANDSHAKE":       1,
	"Net_PING":            2,
	"Contract_Create":     3,
	"Contract_Run":        4,
	"Contract_Query":      5,
	"Code_State_Put":      6,
	"Code_State_Get":      7,
	"Ledger_Block_Create": 8,
	"Ledger_Block_Sync":   9,
	"Identity_Share":      10,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Message struct {
	Action    Action                     `protobuf:"varint,1,opt,name=action,enum=protos.Action" json:"action,omitempty"`
	Type      Message_Type               `protobuf:"varint,2,opt,name=type,enum=protos.Message_Type" json:"type,omitempty"`
	Payload   []byte                     `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterEnum("protos.Type", Type_name, Type_value)
	proto.RegisterEnum("protos.Action", Action_name, Action_value)
	proto.RegisterEnum("protos.Message_Type", Message_Type_name, Message_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Net service

type NetClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Net_ConnectClient, error)
}

type netClient struct {
	cc *grpc.ClientConn
}

func NewNetClient(cc *grpc.ClientConn) NetClient {
	return &netClient{cc}
}

func (c *netClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Net_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Net_serviceDesc.Streams[0], c.cc, "/protos.net/connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &netConnectClient{stream}
	return x, nil
}

type Net_ConnectClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type netConnectClient struct {
	grpc.ClientStream
}

func (x *netConnectClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *netConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Net service

type NetServer interface {
	Connect(Net_ConnectServer) error
}

func RegisterNetServer(s *grpc.Server, srv NetServer) {
	s.RegisterService(&_Net_serviceDesc, srv)
}

func _Net_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetServer).Connect(&netConnectServer{stream})
}

type Net_ConnectServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type netConnectServer struct {
	grpc.ServerStream
}

func (x *netConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *netConnectServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Net_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.net",
	HandlerType: (*NetServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "connect",
			Handler:       _Net_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x40, 0xeb, 0x24, 0xc4, 0xcd, 0x34, 0x49, 0xb7, 0x53, 0x10, 0x56, 0x2e, 0xa0, 0x20, 0xa1,
	0xa8, 0x07, 0x17, 0xc2, 0x81, 0x5e, 0x4d, 0x13, 0x5a, 0x8b, 0xe2, 0x96, 0x75, 0xe0, 0x6a, 0xb9,
	0xf6, 0x60, 0x22, 0xd2, 0x5d, 0x63, 0xaf, 0x0f, 0xfe, 0x0a, 0xbe, 0x90, 0x7f, 0x61, 0x6d, 0xd7,
	0x89, 0x88, 0x38, 0x59, 0xf3, 0xe6, 0xcd, 0xee, 0xcc, 0x8e, 0x61, 0xf4, 0x40, 0x79, 0x1e, 0x26,
	0x64, 0xa7, 0x99, 0x54, 0x12, 0xfb, 0xf5, 0x27, 0x9f, 0xbc, 0x48, 0xa4, 0x4c, 0x36, 0x74, 0x5e,
	0x87, 0xf7, 0xc5, 0xf7, 0x73, 0xb5, 0xd6, 0xa2, 0x0a, 0x1f, 0xd2, 0x46, 0x9c, 0xfe, 0xee, 0x82,
	0xf9, 0xb9, 0x29, 0xc5, 0xd7, 0xd0, 0x0f, 0x23, 0xb5, 0x96, 0xc2, 0x32, 0x5e, 0x1a, 0xb3, 0xf1,
	0x7c, 0xdc, 0x38, 0xb9, 0xed, 0xd4, 0x94, 0x3f, 0x66, 0x71, 0x06, 0x3d, 0x55, 0xa6, 0x64, 0x75,
	0x6a, 0xeb, 0x69, 0x6b, 0x3d, 0x1e, 0x63, 0xaf, 0x74, 0x8e, 0xd7, 0x06, 0x5a, 0x60, 0xa6, 0x61,
	0xb9, 0x91, 0x61, 0x6c, 0x75, 0xb5, 0x3c, 0xe4, 0x6d, 0x88, 0x17, 0x30, 0xd8, 0xb6, 0x62, 0xf5,
	0x74, 0xee, 0x68, 0x3e, 0xb1, 0x9b, 0x66, 0xed, 0xb6, 0x59, 0x7b, 0xd5, 0x1a, 0x7c, 0x27, 0x4f,
	0xff, 0x18, 0xd0, 0xab, 0xae, 0xc0, 0x11, 0x0c, 0xbe, 0x7a, 0x8b, 0xe5, 0x47, 0xd7, 0x5b, 0x2e,
	0xd8, 0x01, 0x9e, 0xc0, 0xc8, 0x23, 0x15, 0x5c, 0x3b, 0xde, 0xc2, 0xbf, 0x76, 0x3e, 0x2d, 0x99,
	0x81, 0x43, 0x38, 0xac, 0xd0, 0x9d, 0xeb, 0x5d, 0xb1, 0x0e, 0x9e, 0xc2, 0xf1, 0xa5, 0x14, 0x2a,
	0xd3, 0x53, 0x04, 0x97, 0x19, 0x85, 0x8a, 0x58, 0x17, 0x19, 0x0c, 0xb7, 0x90, 0x17, 0x82, 0xf5,
	0x10, 0x61, 0xbc, 0x25, 0x5f, 0x0a, 0xca, 0x4a, 0xf6, 0xa4, 0x61, 0x31, 0x05, 0xbe, 0xd2, 0x55,
	0xc1, 0x5d, 0xa1, 0x58, 0x7f, 0x8f, 0x5d, 0x91, 0x62, 0x26, 0x3e, 0x87, 0xd3, 0x1b, 0x8a, 0x13,
	0xca, 0x82, 0x0f, 0x1b, 0x19, 0xfd, 0x6c, 0xaf, 0x39, 0xc4, 0x67, 0x70, 0xf2, 0x4f, 0xc2, 0x2f,
	0x45, 0xc4, 0x06, 0xd5, 0x19, 0x6e, 0x4c, 0x42, 0xad, 0x55, 0x19, 0xf8, 0x3f, 0xc2, 0x8c, 0x18,
	0x9c, 0xbd, 0xff, 0xff, 0x78, 0x3a, 0xfc, 0xe6, 0xdc, 0xb8, 0x0b, 0x67, 0x75, 0xcb, 0xf5, 0x68,
	0xd5, 0xb4, 0xb7, 0x5e, 0xb0, 0x43, 0x9d, 0xb3, 0x57, 0xd0, 0x6f, 0x16, 0x85, 0x47, 0x60, 0x72,
	0xfa, 0x55, 0xe8, 0x07, 0xd3, 0x85, 0xfa, 0x11, 0x38, 0xe5, 0xa9, 0x14, 0x39, 0x31, 0x63, 0x7e,
	0x01, 0x5d, 0x41, 0x0a, 0xdf, 0x82, 0x19, 0x49, 0x21, 0x28, 0x52, 0x78, 0xbc, 0xb7, 0xbf, 0xc9,
	0x3e, 0x98, 0x1e, 0xcc, 0x8c, 0x37, 0xc6, 0x7d, 0xf3, 0x4b, 0xbd, 0xfb, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0xe9, 0x1c, 0x96, 0x6a, 0x02, 0x00, 0x00,
}
