// Code generated by protoc-gen-go.
// source: type.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EndPoint_Type int32

const (
	EndPoint_UNDEFINED     EndPoint_Type = 0
	EndPoint_VALIDATOR     EndPoint_Type = 1
	EndPoint_NON_VALIDATOR EndPoint_Type = 2
)

var EndPoint_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "VALIDATOR",
	2: "NON_VALIDATOR",
}
var EndPoint_Type_value = map[string]int32{
	"UNDEFINED":     0,
	"VALIDATOR":     1,
	"NON_VALIDATOR": 2,
}

func (x EndPoint_Type) String() string {
	return proto.EnumName(EndPoint_Type_name, int32(x))
}
func (EndPoint_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type HandShake_Type int32

const (
	HandShake_UNDEFINED            HandShake_Type = 0
	HandShake_Net_HANDSHAKE_FIRST  HandShake_Type = 1
	HandShake_Net_HANDSHAKE_SECOND HandShake_Type = 2
	HandShake_Net_HANDSHAKE_THIRD  HandShake_Type = 3
)

var HandShake_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "Net_HANDSHAKE_FIRST",
	2: "Net_HANDSHAKE_SECOND",
	3: "Net_HANDSHAKE_THIRD",
}
var HandShake_Type_value = map[string]int32{
	"UNDEFINED":            0,
	"Net_HANDSHAKE_FIRST":  1,
	"Net_HANDSHAKE_SECOND": 2,
	"Net_HANDSHAKE_THIRD":  3,
}

func (x HandShake_Type) String() string {
	return proto.EnumName(HandShake_Type_name, int32(x))
}
func (HandShake_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

type HandShakeResponse_Type int32

const (
	HandShakeResponse_UNDEFINED                     HandShakeResponse_Type = 0
	HandShakeResponse_Net_HANDSHAKE_FIRST_RESPONSE  HandShakeResponse_Type = 1
	HandShakeResponse_Net_HANDSHAKE_SECOND_RESPONSE HandShakeResponse_Type = 2
	HandShakeResponse_Net_HANDSHAKE_THIRD_RESPONSE  HandShakeResponse_Type = 3
)

var HandShakeResponse_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "Net_HANDSHAKE_FIRST_RESPONSE",
	2: "Net_HANDSHAKE_SECOND_RESPONSE",
	3: "Net_HANDSHAKE_THIRD_RESPONSE",
}
var HandShakeResponse_Type_value = map[string]int32{
	"UNDEFINED":                     0,
	"Net_HANDSHAKE_FIRST_RESPONSE":  1,
	"Net_HANDSHAKE_SECOND_RESPONSE": 2,
	"Net_HANDSHAKE_THIRD_RESPONSE":  3,
}

func (x HandShakeResponse_Type) String() string {
	return proto.EnumName(HandShakeResponse_Type_name, int32(x))
}
func (HandShakeResponse_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

type EndPoint struct {
	Id      string        `protobuf:"bytes,1,opt,name=Id,json=id" json:"Id,omitempty"`
	Address string        `protobuf:"bytes,2,opt,name=Address,json=address" json:"Address,omitempty"`
	Type    EndPoint_Type `protobuf:"varint,3,opt,name=type,enum=protos.EndPoint_Type" json:"type,omitempty"`
}

func (m *EndPoint) Reset()                    { *m = EndPoint{} }
func (m *EndPoint) String() string            { return proto.CompactTextString(m) }
func (*EndPoint) ProtoMessage()               {}
func (*EndPoint) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type HandShake struct {
	Type      HandShake_Type             `protobuf:"varint,1,opt,name=type,enum=protos.HandShake_Type" json:"type,omitempty"`
	EndPoint  *EndPoint                  `protobuf:"bytes,2,opt,name=endPoint" json:"endPoint,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *HandShake) Reset()                    { *m = HandShake{} }
func (m *HandShake) String() string            { return proto.CompactTextString(m) }
func (*HandShake) ProtoMessage()               {}
func (*HandShake) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *HandShake) GetEndPoint() *EndPoint {
	if m != nil {
		return m.EndPoint
	}
	return nil
}

func (m *HandShake) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type HandShakeResponse struct {
	Type      HandShakeResponse_Type     `protobuf:"varint,1,opt,name=type,enum=protos.HandShakeResponse_Type" json:"type,omitempty"`
	Msg       []byte                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *HandShakeResponse) Reset()                    { *m = HandShakeResponse{} }
func (m *HandShakeResponse) String() string            { return proto.CompactTextString(m) }
func (*HandShakeResponse) ProtoMessage()               {}
func (*HandShakeResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *HandShakeResponse) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*EndPoint)(nil), "protos.EndPoint")
	proto.RegisterType((*HandShake)(nil), "protos.HandShake")
	proto.RegisterType((*HandShakeResponse)(nil), "protos.HandShakeResponse")
	proto.RegisterEnum("protos.EndPoint_Type", EndPoint_Type_name, EndPoint_Type_value)
	proto.RegisterEnum("protos.HandShake_Type", HandShake_Type_name, HandShake_Type_value)
	proto.RegisterEnum("protos.HandShakeResponse_Type", HandShakeResponse_Type_name, HandShakeResponse_Type_value)
}

func init() { proto.RegisterFile("type.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0xaf, 0x93, 0x40,
	0x14, 0xc5, 0x65, 0x68, 0x6c, 0xb9, 0xb5, 0x0d, 0x1d, 0xff, 0x91, 0xc6, 0x3f, 0x95, 0x95, 0x1a,
	0x43, 0x13, 0x5c, 0xe8, 0x96, 0x08, 0x0d, 0x44, 0x33, 0x34, 0x03, 0xba, 0x25, 0x34, 0x8c, 0xb5,
	0xd1, 0x02, 0xe9, 0xe0, 0xc2, 0xc4, 0xd5, 0xfb, 0x06, 0x6f, 0xf7, 0x3e, 0xee, 0x83, 0xa1, 0x40,
	0xfb, 0xca, 0xee, 0xad, 0xe0, 0xde, 0x7b, 0xb8, 0xe7, 0x9e, 0x5f, 0x00, 0x28, 0xfe, 0xe5, 0xcc,
	0xc8, 0x0f, 0x59, 0x91, 0xe1, 0x87, 0xe2, 0xc1, 0xe7, 0xaf, 0xb7, 0x59, 0xb6, 0xfd, 0xc3, 0x96,
	0xa2, 0xdc, 0xfc, 0xfd, 0xb9, 0x2c, 0x76, 0x7b, 0xc6, 0x8b, 0x78, 0x9f, 0xd7, 0x42, 0xfd, 0x46,
	0x82, 0x91, 0x93, 0x26, 0xeb, 0x6c, 0x97, 0x16, 0x78, 0x0a, 0xc8, 0x4b, 0x34, 0x69, 0x21, 0xbd,
	0x55, 0x28, 0xda, 0x25, 0x58, 0x83, 0xa1, 0x95, 0x24, 0x07, 0xc6, 0xb9, 0x86, 0x44, 0x73, 0x18,
	0xd7, 0x25, 0x7e, 0x07, 0x83, 0xca, 0x4d, 0x93, 0xcb, 0xf6, 0xd4, 0x7c, 0x5a, 0x2f, 0xe3, 0x46,
	0xb3, 0xc9, 0x08, 0xcb, 0x21, 0x15, 0x12, 0xfd, 0x13, 0x0c, 0xaa, 0x0a, 0x4f, 0x40, 0xf9, 0x4e,
	0x6c, 0x67, 0xe5, 0x11, 0xc7, 0x56, 0x1f, 0x54, 0xe5, 0x0f, 0xeb, 0x9b, 0x67, 0x5b, 0xa1, 0x4f,
	0x55, 0x09, 0xcf, 0x60, 0x42, 0x7c, 0x12, 0x75, 0x2d, 0xa4, 0x5f, 0x21, 0x50, 0xdc, 0x38, 0x4d,
	0x82, 0x5f, 0xf1, 0x6f, 0x86, 0xdf, 0x1f, 0x1d, 0x25, 0xe1, 0xf8, 0xac, 0x71, 0x6c, 0x05, 0x27,
	0x96, 0xf8, 0x03, 0x8c, 0xd8, 0xf1, 0x12, 0x71, 0xf8, 0xd8, 0x54, 0xef, 0x5e, 0x48, 0x5b, 0x05,
	0xfe, 0x0c, 0x4a, 0x4b, 0x45, 0x04, 0x1a, 0x9b, 0x73, 0xa3, 0xe6, 0x66, 0x34, 0xdc, 0x8c, 0xb0,
	0x51, 0xd0, 0x4e, 0xac, 0xc7, 0xfd, 0xd1, 0x9e, 0xc3, 0x63, 0xc2, 0x8a, 0xc8, 0xb5, 0x88, 0x1d,
	0xb8, 0xd6, 0x57, 0x27, 0x5a, 0x79, 0x34, 0x08, 0xcb, 0x90, 0x1a, 0x3c, 0x39, 0x1f, 0x04, 0xce,
	0x17, 0x9f, 0xd8, 0x2a, 0xba, 0xfc, 0x24, 0x74, 0x3d, 0x6a, 0xab, 0xb2, 0x7e, 0x8d, 0x60, 0xd6,
	0x66, 0xa4, 0x8c, 0xe7, 0x59, 0xca, 0x19, 0x36, 0xcf, 0x60, 0xbc, 0xba, 0x80, 0xd1, 0x08, 0x4f,
	0xa1, 0xa8, 0x20, 0xef, 0xf9, 0x56, 0xf0, 0x78, 0x44, 0xab, 0xd7, 0x7b, 0x04, 0xff, 0xdf, 0x1f,
	0x7c, 0x01, 0x2f, 0x7a, 0x82, 0x47, 0xd4, 0x09, 0xd6, 0x3e, 0x09, 0x9c, 0x92, 0xc0, 0x1b, 0x78,
	0xd9, 0x47, 0xa0, 0x93, 0xa0, 0xcb, 0x25, 0x02, 0x45, 0xa7, 0x90, 0x37, 0xf5, 0xcf, 0xfd, 0xf1,
	0x36, 0x00, 0x00, 0xff, 0xff, 0x98, 0x8a, 0x08, 0xd4, 0xf1, 0x02, 0x00, 0x00,
}
